{
    "openapi": "3.0.2",
    "info": {
        "description": "به پلتفرم اکسیژن خوش آمدید!\r\n\r\n در این مستندات، اطلاعات جامعی درباره APIهای مربوط به احراز هویت، انتقال وجه، مدیریت چک، صورتحساب و سایر خدمات مالی ارائه شده است.\r\n\r\n هدف این راهنما تسهیل درک و پیاده‌سازی این سرویس‌ها به شیوه‌ای کارآمد و یکپارچه است.",
        "title": ""
    },
    "servers": [
        {
            "url": "/api/v3"
        }
    ],
    "tags": [
        {
            "name": "احراز هویت (Authorization)",
            "description": "",
            "externalDocs": {
                "description": "",
                "url": ""
            }
        }
    ],
    "paths": {
        "/identity/oauth2/auth/token": {
            "post": {
                "summary": "دریافت توکن (OAuth2)",
                "description": "برای استفاده در سایر سرویس های سداد با استفاده از روش (access_token)\r\n\r\n**هدف:** دریافت توکن دسترسی  client_credentils.\r\n\r\n**نکات کلیدی:**\r\n\r\nاین سرویس اولین مرحله برای دسترسی به سایر سرویس ها است.\r\n\r\nتوکن دریافتی دارای زمان انقضاء است و پس از انقضا باید مجددا دریافت شود.\r\n\r\nاحراز هویت  استفاده از clientKey و clientSecret انجام میشود.",
                "operationId": "0001",
                "tags": ["احراز هویت (Authorization)"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "Authorization",
                        "description": "از ترکیب Base64 و با کدگذاری Basic Auth \r\n\r\n**توضیح:** مقدار این هدر باید به صورت clientKey:clientSecret باشد.\r\n\r\n**مثال:**\r\n\r\nplaintext\r\n\r\napplication/x-www-form-urlencoded",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "path",
                        "name": "Content-Type",
                        "description": "**توضیح:** Basic Auth تولید شده با توجه به ClientSecret, ClientKey",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],

                "responses": {
                    "200": {
                        "headers": {},
                        "description": "<div style='float: right;padding: 0 3rem;'>.توکن با موفقیت ایجاد شد</div>",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "string"
                                                },
                                                "timestamps": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "detail": {
                                                                "type": "string"
                                                            },
                                                            "name": {
                                                                "type": "string"
                                                            },
                                                            "summary": {
                                                                "type": "string"
                                                            }
                                                        },
                                                        "required": []
                                                    }
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "number": {
                                                    "type": "number"
                                                }
                                            }
                                        },
                                        "response": {
                                            "type": "object",
                                            "properties": {
                                                "nationalCodes": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        },
                                        "successful": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "example1": {
                                        "value": {
                                            "last_logins": "[]",
                                            "token_type": "bearer",
                                            "expires_in": 86400,
                                            "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJncmFudCI6IkNMSUVOVCIsImlzcyI6Imh0dHA6Ly9hcGkuYm1pLmlyL3NlY3VyaXR5XXXXXXXXXXXXXXXXXXXXXXXXXXXGVzIjpbImxvYW4tYXNzZXQtaW5xLWdvbGQiXX0=.LXAAxYt6zXomW4QV28sCxjLBgMQ2aLzqamMJq6YwzVI"
                                        }
                                    },
                                    "example2": {
                                        "value": {
                                            "last_logins": "[]",
                                            "token_type": "bearer",
                                            "expires_in": 86400,
                                            "access_token": "توکن_دسترسی_اینجا_قرار_می‌گیرد"
                                        }
                                    },
                                    "example3": {
                                        "value": {
                                            "error": {
                                                "code": "string",
                                                "timestamps": "string",
                                                "errors": [
                                                    {
                                                        "detail": "string",
                                                        "name": "string",
                                                        "summary": "string"
                                                    }
                                                ],
                                                "message": "string",
                                                "number": 0
                                            },
                                            "response": {
                                                "nationalCodes": ["string"]
                                            },
                                            "successful": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "<p style='direction: rtl;padding: 0 3rem;float: right;'>پارامترهای ورودی ناقص یا نامعتبر.</p>",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        },
                                        "error_description": {
                                            "type": "string"
                                        }
                                    },
                                    "description": "پاسخ خطا(کد 4XX/5XX)"
                                },
                                "examples": {
                                    "example1": {
                                        "value": {
                                            "error": "CLIENT_NOT_AUTHORIZED",
                                            "error_description": "کلید یا رمز مشتری معتبر نیست."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "<p style='direction: rtl;padding: 0 3rem;float: right;'> عدم احراز هویت صحیح (مثلاً ClientKey یا ClientSecret نادرست).</p>",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        },
                                        "error_description": {
                                            "type": "string"
                                        }
                                    },
                                    "description": "پاسخ خطا(کد 4XX/5XX)"
                                },
                                "examples": {
                                    "example1": {
                                        "value": {
                                            "error": "CLIENT_NOT_AUTHORIZED",
                                            "error_description": "کلید یا رمز مشتری معتبر نیست."
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "scope": {
                                        "type": "number",
                                        "description": "مقدار پیش فرض: scope-client-test (در محیط تست) یا مقدار اختصاصی در محیط عملیاتی"
                                    },
                                    "grant_type": {
                                        "type": "number",
                                        "description": "مقدار ثابت: client-credentials"
                                    }
                                },
                                "required": [
                                    "accountNumber",
                                    "creditDebit",
                                    "field_0"
                                ],
                                "description": "بدنه درخواست"
                            },
                            "examples": {
                                "example1": {
                                    "value": {
                                        "error": {
                                            "code": "کد خطای سیستمی (مثلاً GENERAL_ERROR)",
                                            "timestamp": "2023-11-20T12:00:00Z",
                                            "errors": [
                                                {
                                                    "detail": "توضیح خطای خاص",
                                                    "name": "نام خطا (مثلاً VALIDATION_ERROR)",
                                                    "summary": "خلاصه خطا (مثلاً مقدار ورودی نامعتبر است)"
                                                }
                                            ],
                                            "message": "پیام کلی خطا به زبان خوانا",
                                            "error_number": 1001
                                        },
                                        "response": {
                                            "nationalCodes": [
                                                "1234567890",
                                                "0987654321"
                                            ]
                                        },
                                        "successful": false
                                    }
                                },
                                "example2": {
                                    "value": {
                                        "error": {
                                            "code": "string",
                                            "timestamp": "2023-11-20T12:00:00Z",
                                            "errors": [
                                                {
                                                    "detail": "string",
                                                    "name": "string",
                                                    "summary": "string"
                                                }
                                            ],
                                            "message": "string",
                                            "error_number": 0
                                        },
                                        "response": {
                                            "nationalCodes": ["string"]
                                        },
                                        "successful": true
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "StructureStatementRequest": {
                "type": "object",
                "properties": {
                    "offsetNumber": {
                        "type": "string",
                        "description": "شماره آفست "
                    },
                    "offsetLength": {
                        "type": "string",
                        "description": "طول آفست"
                    },
                    "accountNumber": {
                        "type": "string",
                        "description": "شماره حساب"
                    },
                    "dateTimeRange": {
                        "anyOf": [
                            {
                                "type": "string",
                                "description": "از تاریخ و زمان"
                            },
                            {
                                "type": "string",
                                "description": "تا تاریخ و زمان"
                            }
                        ],
                        "description": "بازه تاریخ و زمان"
                    },
                    "traceNumber": {
                        "type": "string",
                        "description": "شماره پیگی ری تراکنش "
                    },
                    "amountRange": {
                        "type": "string",
                        "description": "بازه مبلغ"
                    },
                    "channel": {
                        "type": "string",
                        "description": "کانال، یکی از مقادیر: \r\npos/internet/teller/atm/pinpad/UNKN\r\nOWN"
                    },
                    "creditDebit": {
                        "type": "string",
                        "description": "نوع تراکنش از نظر واریز/برداشت، یکی از مقادیر: \r\nDEBIT/CREDIT"
                    },
                    "branchCode": {
                        "type": "integer"
                    },
                    "sortType": {
                        "type": "integer",
                        "description": "وع مرتب سازی تراکنش ها جهت ارائه خروجی \r\n)در حالت پیش فرض یا صفر: نزولی، مقدار یک: \r\nصعودی)"
                    },
                    "categoryId": {
                        "type": "string",
                        "description": "شناسه دسته تراکنش "
                    },
                    "languageType": {
                        "type": "string",
                        "description": "نوع زبان، یکی از مقادیر FARSI(فارسی(/\r\nENGLISH(انگلیسی)"
                    }
                },
                "required": [
                    "offsetNumber",
                    "offsetLength",
                    "accountNumber",
                    "dateTimeRange",
                    "traceNumber",
                    "amountRange",
                    "channel",
                    "creditDebit",
                    "branchCode",
                    "sortType",
                    "categoryId",
                    "languageType",
                    "field_0"
                ],
                "description": "ساختار Request"
            }
        },
        "requestBodies": {},
        "securitySchemes": {
            "petstore_auth": {
                "type": "oauth2",
                "flows": {
                    "implicit": {
                        "authorizationUrl": "https://petstore3.swagger.io/oauth/authorize",
                        "scopes": {
                            "write:pets": "modify pets in your account",
                            "read:pets": "read your pets"
                        }
                    }
                }
            },
            "api_key": {
                "type": "apiKey",
                "name": "api_key",
                "in": "header"
            }
        }
    }
}
