{
  "openapi": "3.0.2",
  "info": {
    "title": "راهنمای سرویس های اکسیژن",
    "description": "...",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://uat.developer.oxygenpro.ir/api"
    }
  ],
  "tags": [
    {
      "name": "صورتحساب",
      "description": "سرویس صورتحساب آنلاین \r\n\r\nاین سرویس به منظور دریافت اطلاعات تراکنش های حساب میباشد\r\nبرای تراکنش های روز جاری اطلاعات از بستر \r\nMQ\r\nشرکت خدمات انفورماتیک و برای سایر تراکنش ها اطلاعات از انبار داده استخراج میشود.\r\n\r\n Scope:svc-mgmt-mq-stmt-info",
      "externalDocs": {
        "description": "",
        "url": ""
      }
    }
  ],
  "paths": {
    "/mq-statement/v2/online-statement": {
      "post": {
        "summary": "صورتحساب آنلاین",
        "description": "سرویس صورتحساب آنلاین \r\n\r\nاین سرویس به منظور دریافت اطلاعات تراکنش های حساب میباشد\r\nبرای تراکنش های روز جاری اطلاعات از بستر \r\nMQ\r\nشرکت خدمات انفورماتیک و برای سایر تراکنش ها اطلاعات از انبار داده استخراج میشود.\r\n\r\n Scope:svc-mgmt-mq-stmt-info",
        "tags": [
          "صورتحساب"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "Authorization",
            "description": "برای استفاده از این سرویس ها بایستی ابتدا توکن دسترسی را از سرورهای احراز هویت بانک ملی دریافت نموده و سپس در بخش هدر درخواست ها خود ارسال نمایید.\n",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "path",
            "name": "Content-Type",
            "description": "نوع محتوا",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "null"
                    },
                    "response": {
                      "type": "object",
                      "properties": {
                        "accountStatementResponse": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "transactionDateTime": {
                                "type": "string",
                                "description": "تاریخ و زمان تراکنش"
                              },
                              "transactionTraceCode": {
                                "type": "string",
                                "description": "شماره پیگیری تراکنش"
                              },
                              "creditDebit": {
                                "type": "string",
                                "description": "نوع تراکنش از نظر واریز/ برداشت\r\nDEBIT/CREDIT"
                              },
                              "branchCode": {
                                "type": "number",
                                "description": "کد شعبه عامل"
                              },
                              "operatorCode": {
                                "type": "string",
                                "description": "کد اپراتور"
                              },
                              "additionalData1": {
                                "type": "string",
                                "description": "اطلاعات تکمیلی اول"
                              },
                              "additionalData2": {
                                "type": "string",
                                "description": "اطلاعات تکمیلی دوم"
                              },
                              "transactionCode": {
                                "type": "string",
                                "description": "کد تراکنش"
                              },
                              "realDateTime": {
                                "type": "string",
                                "description": "تاریخ و زمان مالی تراکنش"
                              },
                              "amount": {
                                "type": "number",
                                "description": "مبلغ تراکنش"
                              },
                              "balance": {
                                "type": "number",
                                "description": "مانده تراکنش"
                              },
                              "channelType": {
                                "type": "string",
                                "description": "درگاه تراکنش"
                              },
                              "categoryId": {
                                "type": "string",
                                "description": "شناسه دسته تراکنش در سامانه بام"
                              },
                              "comment": {
                                "type": "string",
                                "description": "توضیحات ثبت شده توسط مشتری"
                              },
                              "hyperLinkType": {
                                "type": "object",
                                "properties": {
                                  "0": {
                                    "type": "string"
                                  },
                                  "1": {
                                    "type": "string",
                                    "description": "تراکنش های سرجمع سدادی"
                                  },
                                  "2": {
                                    "type": "string",
                                    "description": "تراکنش های برداشت پایا"
                                  },
                                  "3": {
                                    "type": "string",
                                    "description": "تراکنش های واریز پایا"
                                  },
                                  "4": {
                                    "type": "string",
                                    "description": "تراکنش های برگشتی پایا"
                                  },
                                  "5": {
                                    "type": "string",
                                    "description": "تراکنش های خرید توسط کارت از درگاه اینترنتی یا دستگاه \r\nPOS"
                                  },
                                  "6": {
                                    "type": "string",
                                    "description": "تراکنش های واریز پایا"
                                  },
                                  "7": {
                                    "type": "string",
                                    "description": "تراکنش های سرجممع شاپرکی غیر سدادی"
                                  },
                                  "8": {
                                    "type": "string",
                                    "description": "تراکنش های واریز و برداشت ساتننا"
                                  },
                                  "field_0": {
                                    "type": "string",
                                    "description": "در تراکنش های روز جاری مقدار این فیلد \r\nNULL\r\n نمایش داده میشود."
                                  }
                                },
                                "description": "نوع لینک تراکنش",
                                "required": [
                                  "1",
                                  "2",
                                  "3",
                                  "4",
                                  "5",
                                  "6",
                                  "7",
                                  "8",
                                  "0",
                                  "field_0"
                                ]
                              },
                              "rowNumber": {
                                "type": "number",
                                "description": "شماره ردیف"
                              },
                              "origKey": {
                                "type": "string",
                                "description": "کلید تراکنش \r\n(از دو مقدار زمان، کد پیگیری تشکیل شده است که تنها برای تراکنش های روز جاری مقدار داشته و درباقی موارد مقدار آن \r\nNULL\r\nمیباشد)"
                              },
                              "channelDateTime": {
                                "type": "string",
                                "description": "زمان تراکنش در کانال"
                              }
                            },
                            "required": [
                              "transactionDateTime",
                              "transactionTraceCode",
                              "creditDebit",
                              "branchCode",
                              "رودبارجنوب ",
                              "operatorCode",
                              "additionalData1",
                              "additionalData2",
                              "transactionCode",
                              "انتقالی ازکارت ",
                              "realDateTime",
                              "amount",
                              "balance",
                              "channelType",
                              "categoryId",
                              "comment",
                              "hyperLinkType",
                              "rowNumber",
                              "origKey",
                              "channelDateTime",
                              "field_0"
                            ]
                          }
                        },
                        "outputRecordCount": {
                          "type": "number"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "example1": {
                    "value": {
                      "error": null,
                      "response": {
                        "accountStatementResponse": [
                          {
                            "transactionDateTime": "string",
                            "transactionTraceCode": "string",
                            "creditDebit": "string",
                            "branchCode": 0,
                            "operatorCode": "string",
                            "additionalData1": "string",
                            "additionalData2": "string",
                            "transactionCode": "string",
                            "realDateTime": "string",
                            "amount": 0,
                            "balance": 0,
                            "channelType": "string",
                            "categoryId": "string",
                            "comment": "string",
                            "hyperLinkType": {
                              "0": "string",
                              "1": "string",
                              "2": "string",
                              "3": "string",
                              "4": "string",
                              "5": "string",
                              "6": "string",
                              "7": "string",
                              "8": "string",
                              "field_0": "string"
                            },
                            "rowNumber": 0,
                            "origKey": "string",
                            "channelDateTime": "string"
                          }
                        ],
                        "outputRecordCount": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "headers": {
              "Number": {
                "description": "",
                "schema": {
                  "type": "string"
                }
              },
              "Code": {
                "description": "",
                "schema": {
                  "type": "string"
                }
              },
              "Message": {
                "description": "",
                "schema": {
                  "type": "string"
                }
              },
              "Timestamp": {
                "description": "",
                "schema": {
                  "type": "string"
                }
              },
              "Errors": {
                "description": "",
                "schema": {
                  "type": "object"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "string",
                          "description": "این کد به صورت رشته میباشد\r\nبه عنوان مثال:\r\nCONSTRAINT_VIOLATION_EXCEPTION"
                        },
                        "message": {
                          "type": "string"
                        },
                        "timestamp": {
                          "type": "string",
                          "description": "تاریخ با فرمت \r\nyyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
                        },
                        "errors": {
                          "type": "object",
                          "properties": {
                            "Name": {
                              "type": "string",
                              "description": "نام فیلدی که در اعتبارسنجی با خطا مواجه شده است"
                            },
                            "Summary": {
                              "type": "string",
                              "description": "خلاصه خطا"
                            },
                            "Detail": {
                              "type": "string",
                              "description": "جزئیات خطا"
                            }
                          },
                          "description": "این فیلد در هنگام ایجاد خطا در اعتبارسنجی مقادیر ورودی پر میشود",
                          "required": [
                            "Name",
                            "Summary",
                            "Detail"
                          ]
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "example1": {
                    "value": {
                      "error": {
                        "code": "string",
                        "message": "string",
                        "timestamp": "string",
                        "domain": "string",
                        "errors": [
                          "string"
                        ]
                      },
                      "response": null
                    }
                  }
                }
              }
            }
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "offsetNumber": {
                    "type": "number",
                    "description": "شماره آفست \r\nپیش فرض : 1"
                  },
                  "offsetLength": {
                    "type": "number",
                    "description": "طول آفست \r\nپیش فرض : 20"
                  },
                  "accountNumber": {
                    "type": "string",
                    "description": "شماره حساب"
                  },
                  "dateTimeRange": {
                    "type": "object",
                    "properties": {
                      "fromDateTime": {
                        "type": "string"
                      },
                      "toDateTime": {
                        "type": "string"
                      }
                    },
                    "description": "بازه تاریخ و زمان "
                  },
                  "traceNumber": {
                    "type": "string",
                    "description": "شماره پیگیری تراکنش"
                  },
                  "amountRange": {
                    "type": "object",
                    "properties": {
                      "fromAmount": {
                        "type": "integer",
                        "description": "از مبلغ"
                      },
                      "toAmount": {
                        "type": "integer",
                        "description": "تا مبلغ"
                      }
                    },
                    "description": "بازه مبلغ",
                    "required": [
                      "fromAmount",
                      "toAmount"
                    ]
                  },
                  "channel": {
                    "type": "string",
                    "description": "کانال، یکی از مقادیر \r\npos/internet/teller/atm/pinpad/UNKN\r\nOWN"
                  },
                  "creditDebit": {
                    "type": "string",
                    "description": "نوع تراکنش از نظر واریز/برداشت، یکی از مقادیر: \r\nDEBIT/CREDIT"
                  },
                  "branchCode": {
                    "type": "integer",
                    "description": "کد شعبه"
                  },
                  "sortType": {
                    "type": "integer",
                    "description": "نوع مرتب سازی تراکنش ها جهت ارائه خروجی \r\n)در حالت پیش فرض یا صفر: نزولی، مقدار یک: \r\nصعودی("
                  },
                  "categoryId": {
                    "type": "integer",
                    "description": "شناسه دسته تراکنش"
                  },
                  "languageType": {
                    "type": "string",
                    "description": "نوع زبان، یکی از مقادیر \r\nFARSI فارسی\r\nENGLISH انگلیسی"
                  }
                },
                "required": [
                  "accountNumber",
                  "creditDebit",
                  "field_0"
                ]
              },
              "examples": {
                "example1": {
                  "value": {
                    "offsetNumber": 0,
                    "offsetLength": 0,
                    "accountNumber": "string",
                    "dateTimeRange": {
                      "fromDateTime": "string",
                      "toDateTime": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/transfer/single/create": {
      "post": {
        "summary": "درخواست انتقال پول تکی",
        "description": "سرویس درخواست انتقال پول \r\n\r\nبا استفاده از این سرویس امکان ثبت و انتقال پول میسر می باشد\r\n\r\nscope: money-transfer\r\n",
        "tags": [
          "صورتحساب"
        ],
        "parameters": [
          {
            "in": "header",
            "name": "submit",
            "description": "False(Default)",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "in": "header",
            "name": "ignoreHints",
            "description": "True(Default)",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "in": "header",
            "name": "Channel",
            "description": "ISC_TM یا ISC_MB",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "resultSet": {
                      "type": "object",
                      "properties": {
                        "innerResponse": {
                          "type": "object",
                          "properties": {
                            "items": {
                              "type": "string",
                              "description": "لیست تراکنش \r\n(مخصوص انتقال\r\nbatch,recurring)"
                            },
                            "scheduledTransfer": {
                              "type": "string",
                              "description": "نوع تراکنش"
                            },
                            "id": {
                              "type": "string",
                              "description": "GUID"
                            },
                            "alias": {
                              "type": "string",
                              "description": "عنوان"
                            },
                            "accountId": {
                              "type": "string",
                              "description": "شماره حساب مبدا"
                            },
                            "instructedAmount": {
                              "type": "number",
                              "description": "مبلغ"
                            },
                            "instructedCurrency": {
                              "type": "string",
                              "description": "IRR\r\n(ثابت)"
                            },
                            "counterpartyName": {
                              "type": "string",
                              "description": "نام صاحب حساب مقصد"
                            },
                            "counterpartyAccount": {
                              "type": "string",
                              "description": "شماره حساب مقصد"
                            },
                            "paymentReference": {
                              "type": "string",
                              "description": "شناسه واریز"
                            },
                            "paymentDescription": {
                              "type": "string",
                              "description": "توضیحات"
                            },
                            "causeDescription": {
                              "type": "string",
                              "description": "شرح دلیل"
                            },
                            "method": {
                              "type": "string",
                              "description": "نوع انتقال پول شامل \r\n(توضیحات تکمیلی در ساختار Response)"
                            },
                            "mode": {
                              "type": "string",
                              "description": "حالت انتقال پول \r\n(ثابت single)"
                            },
                            "totalAmount": {
                              "type": "number",
                              "description": "مبلغ کل انتقالی "
                            },
                            "totalCount": {
                              "type": "number",
                              "description": "تعداد تراکنش ها"
                            },
                            "creatorName": {
                              "type": "string",
                              "description": "نام ایجاد کننده انتقال پول "
                            },
                            "status": {
                              "type": "string",
                              "description": "وضعیت اتقال پول "
                            },
                            "initiationDateTime": {
                              "type": "string",
                              "description": "تاریخ ایجاد تراکنش"
                            },
                            "updateDateTime": {
                              "type": "string",
                              "description": "تاریخ آخرین تغییرات "
                            },
                            "onDate": {
                              "type": "string",
                              "description": "تاریخ روز"
                            },
                            "confirmationDateTime": {
                              "type": "string",
                              "description": "زمان تایید تراکنش"
                            },
                            "traceNo": {
                              "type": "string",
                              "description": "شماره پیگیری"
                            },
                            "extraTraceNo": {
                              "type": "string"
                            },
                            "responseCode": {
                              "type": "string",
                              "description": "کد پاسخ"
                            },
                            "responseMessage": {
                              "type": "boolean",
                              "description": "پیغام پاسخ"
                            },
                            "archived": {
                              "type": "boolean",
                              "description": "بایگانی"
                            },
                            "creatorSSN": {
                              "type": "string",
                              "description": "کد ملی ایجادکننده انتقال پول"
                            },
                            "creditPayId": {
                              "type": "string",
                              "description": "شناسه واریز"
                            },
                            "debitPayId": {
                              "type": "string",
                              "description": "شناسه برداشت"
                            }
                          }
                        }
                      }
                    },
                    "metaData": {
                      "type": "object",
                      "properties": {
                        "notifications": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "code": {
                                "type": "string"
                              },
                              "type": {
                                "type": "string"
                              },
                              "message": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "example1": {
                    "value": {
                      "resultSet": {
                        "innerResponse": {
                          "items": null,
                          "scheduledTransfer": null,
                          "id": "string",
                          "alias": "string",
                          "accountId": "string",
                          "instructedAmount": 0,
                          "instructedCurrency": "string",
                          "counterpartyName": "string",
                          "counterpartyAccount": "string",
                          "paymentReference": "string",
                          "paymentDescription": "string",
                          "causeDescription": null,
                          "method": "string",
                          "mode": "string",
                          "totalAmount": 0,
                          "totalCount": 0,
                          "creatorName": null,
                          "status": "string",
                          "initiationDateTime": "string",
                          "updateDateTime": null,
                          "onDate": "string",
                          "confirmationDateTime": null,
                          "traceNo": null,
                          "extraTraceNo": null,
                          "responseCode": null,
                          "responseMessage": null,
                          "archived": true,
                          "creatorSSN": "string",
                          "creditPayId": null,
                          "debitPayId": null
                        }
                      },
                      "metaData": {
                        "notifications": [
                          {
                            "code": "string",
                            "type": "string",
                            "message": "string"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "notifications": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "code": {
                            "type": "string"
                          },
                          "type": {
                            "type": "string"
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "description": "لیست تراکنش",
                        "required": []
                      }
                    }
                  }
                },
                "examples": {
                  "example1": {
                    "value": {
                      "notifications": [
                        {
                          "code": "string",
                          "type": "string",
                          "message": "string"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "alias": {
                    "type": "string",
                    "description": "عنوان تراکنش"
                  },
                  "id": {
                    "type": "string",
                    "description": "GUID"
                  },
                  "accountId": {
                    "type": "string",
                    "description": "شماره حساب مبدا"
                  },
                  "instructedAmount": {
                    "type": "number",
                    "description": "مبلغ"
                  },
                  "instructedCurrency": {
                    "type": "string",
                    "description": "نوع ارز\r\n(ثابت IRR)"
                  },
                  "counterpartyName": {
                    "type": "string",
                    "description": "نام صاحب حساب مقصد"
                  },
                  "counterpartyAccount": {
                    "type": "string",
                    "description": "شماره تسهیالت/شماره حساب مقصد"
                  },
                  "paymentReference": {
                    "type": "string",
                    "description": "شماره ارجاع"
                  },
                  "paymentDescription": {
                    "type": "string",
                    "description": "توضیحات پرداخت"
                  },
                  "onDate": {
                    "type": "number",
                    "description": "بر حسب میلی ثانیه تاریخ روز"
                  },
                  "creditPayId": {
                    "type": "string",
                    "description": "شناسه واریز"
                  },
                  "debitPayId": {
                    "type": "string",
                    "description": "شناسه برداشت"
                  },
                  "causeDescription": {
                    "type": "string",
                    "description": "شرح دلیل"
                  },
                  "transferMethod": {
                    "type": "object",
                    "properties": {
                      " ACCOUNTS_INT": {
                        "type": "string",
                        "description": "تراکنش انتقال پول بین حسابهای خود"
                      },
                      "INTRA_BANK": {
                        "type": "string",
                        "description": "تراکنش انتقال پول درون بانکی"
                      },
                      "PAYA": {
                        "type": "string",
                        "description": "تراکنش های انتقال پول بین بانکی کمتر از 500 میلیون ریال"
                      },
                      "SATNA": {
                        "type": "string",
                        "description": "تراکنش های انتقال پول بین بانکی بیشتر از 500 میلیون ریال"
                      },
                      "POL": {
                        "type": "string",
                        "description": "تراکنش های انتقال پول بین بانکی از بستر پل"
                      },
                      "mode": {
                        "type": "string",
                        "description": "single\r\nتراکنش تکی"
                      }
                    },
                    "description": "روش انتقال",
                    "required": [
                      " ACCOUNTS_INT",
                      "INTRA_BANK",
                      "PAYA",
                      "SATNA",
                      "POL",
                      "mode"
                    ]
                  },
                  "purpose": {
                    "type": "object",
                    "properties": {
                      "DRPA": {
                        "type": "string",
                        "description": "تادیه دیون"
                      },
                      "POSA": {
                        "type": "string",
                        "description": "واریز حقوق"
                      },
                      "IOSP": {
                        "type": "string",
                        "description": "امور بیمه خدمات"
                      },
                      "HIPA": {
                        "type": "string",
                        "description": "امور درمانی"
                      },
                      "ISAP": {
                        "type": "string",
                        "description": "امور سرمایه گذاری و بورس"
                      },
                      "FXAP": {
                        "type": "string",
                        "description": "امور ارزی"
                      },
                      "RTAP": {
                        "type": "string",
                        "description": "امور بازنشستگی"
                      },
                      "MPTP": {
                        "type": "string",
                        "description": "معاملات اموال منقول"
                      },
                      "IMPT": {
                        "type": "string",
                        "description": "معامالت اموال غیرمنقول"
                      },
                      "LMAP": {
                        "type": "string",
                        "description": "مدیریت نقدینگی"
                      },
                      "CDAP": {
                        "type": "string",
                        "description": "عوارض گمرکی"
                      },
                      "TCAP": {
                        "type": "string",
                        "description": "تسویه مالی"
                      },
                      "GEAC": {
                        "type": "string",
                        "description": "سایرخدمات دولتی"
                      },
                      "LRPA": {
                        "type": "string",
                        "description": "بازپرداخت تسهیلات"
                      },
                      "CCPA": {
                        "type": "string",
                        "description": "تودیع وثیقه"
                      },
                      "GPAC": {
                        "type": "string",
                        "description": "هزینه عمومی و امور روزمره"
                      },
                      "CPAC": {
                        "type": "string",
                        "description": "کمک های نقدی و خیریه"
                      }
                    },
                    "description": "برای انتقال درون بانکی اختیاری\r\nبرای انتقال درون حسابی اختیاری \r\nبرای انتقال بین بانکی اجباری",
                    "required": [
                      "DRPA",
                      "POSA",
                      "IOSP",
                      "HIPA",
                      "ISAP",
                      "FXAP",
                      "RTAP",
                      "MPTP",
                      "IMPT",
                      "LMAP",
                      "CDAP",
                      "TCAP",
                      "GEAC",
                      "LRPA",
                      "CCPA",
                      "GPAC",
                      "CPAC"
                    ]
                  },
                  "shahabCode": {
                    "type": "string",
                    "description": "کد شهاب"
                  },
                  "postalCode": {
                    "type": "string",
                    "description": "کد پستی"
                  },
                  "smtCode": {
                    "type": "string",
                    "description": "نوع واریز"
                  }
                },
                "required": [
                  "id",
                  "accountId",
                  "instructedAmount",
                  "instructedCurrency",
                  "counterpartyName",
                  "counterpartyAccount",
                  "onDate",
                  "purpose",
                  "field_0"
                ]
              },
              "examples": {
                "example1": {
                  "value": {
                    "alias": "string",
                    "id": "string",
                    "accountId": "string",
                    "instructedAmount": 0,
                    "instructedCurrency": "string",
                    "counterpartyName": "string",
                    "counterpartyAccount": "string",
                    "paymentReference": "string",
                    "paymentDescription": "string",
                    "onDate": 0,
                    "creditPayId": "string",
                    "debitPayId": "string",
                    "causeDescription": "string",
                    "transferMethod": 0,
                    "purpose": 0,
                    "shahabCode": "string",
                    "postalCode": "string",
                    "smtCode": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "StructureStatementRequest": {
        "type": "object",
        "properties": {
          "offsetNumber": {
            "type": "string",
            "description": "شماره آفست "
          },
          "offsetLength": {
            "type": "string",
            "description": "طول آفست"
          },
          "accountNumber": {
            "type": "string",
            "description": "شماره حساب"
          },
          "dateTimeRange": {
            "anyOf": [
              {
                "type": "string",
                "description": "از تاریخ و زمان"
              },
              {
                "type": "string",
                "description": "تا تاریخ و زمان"
              }
            ],
            "description": "بازه تاریخ و زمان"
          },
          "traceNumber": {
            "type": "string",
            "description": "شماره پیگی ری تراکنش "
          },
          "amountRange": {
            "type": "string",
            "description": "بازه مبلغ"
          },
          "channel": {
            "type": "string",
            "description": "کانال، یکی از مقادیر: \r\npos/internet/teller/atm/pinpad/UNKN\r\nOWN"
          },
          "creditDebit": {
            "type": "string",
            "description": "نوع تراکنش از نظر واریز/برداشت، یکی از مقادیر: \r\nDEBIT/CREDIT"
          },
          "branchCode": {
            "type": "integer"
          },
          "sortType": {
            "type": "integer",
            "description": "وع مرتب سازی تراکنش ها جهت ارائه خروجی \r\n)در حالت پیش فرض یا صفر: نزولی، مقدار یک: \r\nصعودی)"
          },
          "categoryId": {
            "type": "string",
            "description": "شناسه دسته تراکنش "
          },
          "languageType": {
            "type": "string",
            "description": "نوع زبان، یکی از مقادیر FARSI(فارسی(/\r\nENGLISH(انگلیسی)"
          }
        },
        "required": [
          "offsetNumber",
          "offsetLength",
          "accountNumber",
          "dateTimeRange",
          "traceNumber",
          "amountRange",
          "channel",
          "creditDebit",
          "branchCode",
          "sortType",
          "categoryId",
          "languageType",
          "field_0"
        ],
        "description": "ساختار Request"
      },
      "loan-balance": {
        "type": "object",
        "properties": {}
      }
    },
    "requestBodies": {},
    "securitySchemes": {
      "petstore_auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://petstore3.swagger.io/oauth/authorize",
            "scopes": {
              "write:pets": "modify pets in your account",
              "read:pets": "read your pets"
            }
          }
        }
      },
      "api_key": {
        "type": "apiKey",
        "name": "api_key",
        "in": "header"
      }
    }
  }
}
